targets:
  $default:
    builders:
      testsweets_generator|automation_key_generator:
        enabled: true

builders:
  testsweets_generator|automation_key_generator:
    import: "package:testsweets_generator/testsweets_generator.dart"
    builder_factories: ["automationKeyGenerator"]
    build_extensions: { "$lib$": ["all_files.txt"] }
    auto_apply: dependents
    build_to: source
