name: testsweets_shared
description: Shared models between the TestSweets application and the package
version: 1.0.0
repository: https://github.com/FilledStacks/testsweets
homepage: https://www.testsweets.com/


environment:
  sdk: ^3.3.0

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  
