name: testsweets
description: A package to help sync flutter automation data with TestSweets backend
version: 1.8.5
homepage: https://github.com/FilledStacks/testsweets

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
    
  http: ^0.13.3
  auto_size_text: ^3.0.0
  yaml: ^3.0.0
  meta: ^1.3.0
  get_it: ^7.2.0
  provider: ^6.0.2
  freezed_annotation: ^1.0.0
  json_annotation: ^4.1.0
  stacked: ^2.2.8
  stacked_services: ^0.8.16
  logger: ^1.1.0
  recase: ^4.0.0
  solid_bottom_sheet: ^0.1.10
  flutter_svg: ^1.0.3
  collection: ^1.15.0
  async: ^2.8.2
dev_dependencies:


  stacked_generator: ^0.5.0

  build_runner: ^2.0.5
  freezed: ^1.1.0
  json_serializable: ^6.1.5
  mockito: ^5.0.16


flutter:

  assets:
   - assets/svgs/

