name: testsweets
description: A new Flutter package project.
version: 1.3.2+2
homepage: https://github.com/FilledStacks/testsweets

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  auto_size_text: ^3.0.0-nullsafety.0
  yaml: ^3.0.0
  meta: ^1.3.0
  get_it: ^7.2.0

dev_dependencies:
  mockito:
  test: any
  build_runner:
