name: testsweets
description: A no-code test automation tool that turns any tester into an automation engineer
version: 1.12.0
homepage: https://github.com/FilledStacks/testsweets

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  http: ^1.1.0
  auto_size_text: ^3.0.0
  yaml: ^3.0.0
  meta: ^1.3.0
  get_it: ^7.2.0
  provider: ^6.0.2
  freezed_annotation: ^2.4.1 
  json_annotation: ^4.8.1
  stacked: ^3.4.1
  logger: ^1.1.0
  recase: ^4.0.0
  solid_bottom_sheet: ^0.1.10
  flutter_svg: ^2.0.7
  collection: ^1.15.0
  hive_flutter: ^1.1.0
  path: ^1.9.0
  
dev_dependencies:
  stacked_generator: ^1.5.0
  build_runner: ^2.0.5
  freezed: ^2.4.1
  json_serializable: 
  mockito: ^5.0.16


flutter:

  assets:
   - assets/svgs/

