name: testsweets
description: A new Flutter package project.
version: 0.2.1
homepage: https://github.com/FilledStacks/testsweets

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  auto_size_text: ^2.1.0
  yaml: ^2.2.1
  meta: ^1.2.4
  get_it: ^5.0.6
  args: ^1.6.0

dev_dependencies:
  mockito:
  test: any
