name: testsweets
description: A package to help sync flutter automation data with TestSweets backend
version: 1.8.6+2
homepage: https://github.com/FilledStacks/testsweets

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  http: ^0.13.3
  auto_size_text: ^3.0.0
  yaml: ^3.0.0
  meta: ^1.3.0
  get_it: ^7.2.0
  provider: ^6.0.2
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  stacked: ^2.2.8
  stacked_services: ^0.8.16
  logger: ^1.1.0
  recase: ^4.0.0
  solid_bottom_sheet: ^0.1.10
  flutter_svg: ^1.0.3
  collection: ^1.15.0
  
dev_dependencies:
  stacked_generator: ^0.5.0
  build_runner: ^2.0.5
  freezed: ^0.14.5
  json_serializable: ^5.0.2
  mockito: ^5.0.16


flutter:

  assets:
   - assets/svgs/

