name: testsweets
description: A new Flutter package project.
version: 0.3.0
homepage: https://github.com/FilledStacks/testsweets

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  auto_size_text: ^3.0.0-nullsafety.0
  yaml: ^3.0.0
  meta: ^1.3.0
  get_it: ^6.0.0

dev_dependencies:
  mocktail: ^0.1.1
  test: any
